// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsIz2UxIv02TDy6IFLnTJQv1fBN-kliQ',
    appId: '1:1083590062244:web:3b5f63a9e664cbf9537631',
    messagingSenderId: '1083590062244',
    projectId: 'memoria-1e7c2',
    authDomain: 'memoria-1e7c2.firebaseapp.com',
    storageBucket: 'memoria-1e7c2.appspot.com',
    measurementId: 'G-PJ2QLYCNQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyYEWJiAntVSrGZvR-wX1PTC4UAh7ICU',
    appId: '1:1083590062244:android:25d9970a3051c67d537631',
    messagingSenderId: '1083590062244',
    projectId: 'memoria-1e7c2',
    storageBucket: 'memoria-1e7c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7Xqi4MmT9kTdZWvdAGrenr4PnygEKmg',
    appId: '1:1083590062244:ios:8e343def45aa5aa1537631',
    messagingSenderId: '1083590062244',
    projectId: 'memoria-1e7c2',
    storageBucket: 'memoria-1e7c2.appspot.com',
    iosClientId: '1083590062244-tumq8cv0n013orneduiu1ci72lgan9cp.apps.googleusercontent.com',
    iosBundleId: 'com.gmail.memoria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW7Xqi4MmT9kTdZWvdAGrenr4PnygEKmg',
    appId: '1:1083590062244:ios:db9b7258612bb7ed537631',
    messagingSenderId: '1083590062244',
    projectId: 'memoria-1e7c2',
    storageBucket: 'memoria-1e7c2.appspot.com',
    iosClientId: '1083590062244-lvii6ags2r21n1r75ucshj64d8eq0vqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoria',
  );
}
